# Generated by Django 5.2.9 on 2025-12-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_nickname_user_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
    ]
