# Generated by Django 5.2.9 on 2025-12-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issuenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuenode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_nodes/'),
        ),
    ]
