# Generated by Django 5.2.9 on 2025-12-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issueimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='issueimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
