# Generated by Django 5.2.9 on 2025-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issueimage_options_issueimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue/nodes/'),
        ),
    ]
