# Generated by Django 5.2.9 on 2025-12-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issueimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='location',
        ),
    ]
