# Generated by Django 5.2.9 on 2025-12-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_remove_issue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_pic', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='issuenode',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='issues.issue'),
        ),
        migrations.DeleteModel(
            name='IssueProgress',
        ),
    ]
